# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Sun Apr 29 10:09:03 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 805)
        MainWindow.setBaseSize(QtCore.QSize(800, 800))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fluid = FluidWidget(self.centralwidget)
        self.fluid.setGeometry(QtCore.QRect(0, 0, 800, 608))
        self.fluid.setObjectName("fluid")
        self.advanced = QtGui.QGroupBox(self.centralwidget)
        self.advanced.setGeometry(QtCore.QRect(10, 690, 711, 96))
        self.advanced.setFlat(False)
        self.advanced.setCheckable(False)
        self.advanced.setObjectName("advanced")
        self.layoutWidget = QtGui.QWidget(self.advanced)
        self.layoutWidget.setGeometry(QtCore.QRect(17, 20, 691, 68))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.smoothing_iterations = QtGui.QSlider(self.layoutWidget)
        self.smoothing_iterations.setMinimumSize(QtCore.QSize(200, 0))
        self.smoothing_iterations.setMaximum(100)
        self.smoothing_iterations.setOrientation(QtCore.Qt.Horizontal)
        self.smoothing_iterations.setObjectName("smoothing_iterations")
        self.gridLayout.addWidget(self.smoothing_iterations, 0, 1, 1, 1)
        self.smoothing_iterations_spin = QtGui.QSpinBox(self.layoutWidget)
        self.smoothing_iterations_spin.setMaximum(100)
        self.smoothing_iterations_spin.setObjectName("smoothing_iterations_spin")
        self.gridLayout.addWidget(self.smoothing_iterations_spin, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.smoothing_z_contrib = QtGui.QSlider(self.layoutWidget)
        self.smoothing_z_contrib.setMinimumSize(QtCore.QSize(200, 0))
        self.smoothing_z_contrib.setMaximum(100)
        self.smoothing_z_contrib.setOrientation(QtCore.Qt.Horizontal)
        self.smoothing_z_contrib.setObjectName("smoothing_z_contrib")
        self.gridLayout.addWidget(self.smoothing_z_contrib, 1, 1, 1, 1)
        self.smoothing_z_contrib_out = QtGui.QSpinBox(self.layoutWidget)
        self.smoothing_z_contrib_out.setMaximum(100)
        self.smoothing_z_contrib_out.setObjectName("smoothing_z_contrib_out")
        self.gridLayout.addWidget(self.smoothing_z_contrib_out, 1, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.blur_thickness_map = QtGui.QCheckBox(self.layoutWidget)
        self.blur_thickness_map.setObjectName("blur_thickness_map")
        self.verticalLayout.addWidget(self.blur_thickness_map)
        self.render_mean_curvature = QtGui.QCheckBox(self.layoutWidget)
        self.render_mean_curvature.setObjectName("render_mean_curvature")
        self.verticalLayout.addWidget(self.render_mean_curvature)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 620, 484, 65))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rm_points = QtGui.QPushButton(self.groupBox)
        self.rm_points.setCheckable(True)
        self.rm_points.setAutoExclusive(True)
        self.rm_points.setObjectName("rm_points")
        self.horizontalLayout.addWidget(self.rm_points)
        self.rm_balls = QtGui.QPushButton(self.groupBox)
        self.rm_balls.setCheckable(True)
        self.rm_balls.setAutoExclusive(True)
        self.rm_balls.setObjectName("rm_balls")
        self.horizontalLayout.addWidget(self.rm_balls)
        self.rm_advanced = QtGui.QPushButton(self.groupBox)
        self.rm_advanced.setCheckable(True)
        self.rm_advanced.setAutoExclusive(True)
        self.rm_advanced.setObjectName("rm_advanced")
        self.horizontalLayout.addWidget(self.rm_advanced)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.paused = QtGui.QCheckBox(self.layoutWidget1)
        self.paused.setObjectName("paused")
        self.horizontalLayout_2.addWidget(self.paused)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.smoothing_iterations_spin, QtCore.SIGNAL("valueChanged(int)"), self.smoothing_iterations.setValue)
        QtCore.QObject.connect(self.smoothing_iterations, QtCore.SIGNAL("valueChanged(int)"), self.smoothing_iterations_spin.setValue)
        QtCore.QObject.connect(self.smoothing_z_contrib, QtCore.SIGNAL("valueChanged(int)"), self.smoothing_z_contrib_out.setValue)
        QtCore.QObject.connect(self.smoothing_z_contrib_out, QtCore.SIGNAL("valueChanged(int)"), self.smoothing_z_contrib.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PySPH", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced.setTitle(QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Smoothing iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Smoothing Z-contrib", None, QtGui.QApplication.UnicodeUTF8))
        self.blur_thickness_map.setText(QtGui.QApplication.translate("MainWindow", "Blur thickness map", None, QtGui.QApplication.UnicodeUTF8))
        self.render_mean_curvature.setText(QtGui.QApplication.translate("MainWindow", "Show mean curvature", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Render mode", None, QtGui.QApplication.UnicodeUTF8))
        self.rm_points.setText(QtGui.QApplication.translate("MainWindow", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.rm_balls.setText(QtGui.QApplication.translate("MainWindow", "Balls", None, QtGui.QApplication.UnicodeUTF8))
        self.rm_advanced.setText(QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.paused.setText(QtGui.QApplication.translate("MainWindow", "Paused", None, QtGui.QApplication.UnicodeUTF8))

from fluid_widget import FluidWidget
